<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 2 Regresión Lineal Simple | Modelos de Regresión: Una aproximación práctica con R</title>
  <meta name="description" content="Este libro recopila mi años de experiencia en el aprendizaje de R (R Core Team 2019), y está escrito como una guía para aquellos que recién comienzan." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 2 Regresión Lineal Simple | Modelos de Regresión: Una aproximación práctica con R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Este libro recopila mi años de experiencia en el aprendizaje de R (R Core Team 2019), y está escrito como una guía para aquellos que recién comienzan." />
  <meta name="github-repo" content="https://github.com/jivelez/book-adii" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 2 Regresión Lineal Simple | Modelos de Regresión: Una aproximación práctica con R" />
  
  <meta name="twitter:description" content="Este libro recopila mi años de experiencia en el aprendizaje de R (R Core Team 2019), y está escrito como una guía para aquellos que recién comienzan." />
  

<meta name="author" content="Jorge I. Vélez" />


<meta name="date" content="2021-09-14" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro.html"/>
<link rel="next" href="rlm.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Modelos de Regresión con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenido</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#estructura-del-libro"><i class="fa fa-check"></i>Estructura del libro</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-y-convenciones"><i class="fa fa-check"></i>Software y convenciones</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#bloques-informativos"><i class="fa fa-check"></i>Bloques informativos</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#dedicatoria"><i class="fa fa-check"></i>Dedicatoria</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#sobre-el-autor"><i class="fa fa-check"></i>Sobre el autor</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#analítica-de-datos"><i class="fa fa-check"></i><b>1.1</b> Analítica de Datos</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="intro.html"><a href="intro.html#conceptos-básicos"><i class="fa fa-check"></i><b>1.1.1</b> Conceptos básicos</a></li>
<li class="chapter" data-level="1.1.2" data-path="intro.html"><a href="intro.html#gráficos-básicos"><i class="fa fa-check"></i><b>1.1.2</b> Gráficos básicos</a></li>
<li class="chapter" data-level="1.1.3" data-path="intro.html"><a href="intro.html#tópicos-avanzados"><i class="fa fa-check"></i><b>1.1.3</b> Tópicos avanzados</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#r"><i class="fa fa-check"></i><b>1.2</b> <code>R</code></a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="intro.html"><a href="intro.html#por-qué-r"><i class="fa fa-check"></i><b>1.2.1</b> Por qué <code>R</code>?</a></li>
<li class="chapter" data-level="1.2.2" data-path="intro.html"><a href="intro.html#cran"><i class="fa fa-check"></i><b>1.2.2</b> <code>CRAN</code></a></li>
<li class="chapter" data-level="1.2.3" data-path="intro.html"><a href="intro.html#descarga-e-instalación"><i class="fa fa-check"></i><b>1.2.3</b> Descarga e instalación</a></li>
<li class="chapter" data-level="1.2.4" data-path="intro.html"><a href="intro.html#paquetes"><i class="fa fa-check"></i><b>1.2.4</b> Paquetes</a></li>
<li class="chapter" data-level="1.2.5" data-path="intro.html"><a href="intro.html#operadores-básicos"><i class="fa fa-check"></i><b>1.2.5</b> Operadores básicos</a></li>
<li class="chapter" data-level="1.2.6" data-path="intro.html"><a href="intro.html#creación-de-funciones"><i class="fa fa-check"></i><b>1.2.6</b> Creación de funciones</a></li>
<li class="chapter" data-level="1.2.7" data-path="intro.html"><a href="intro.html#obteniendo-ayuda"><i class="fa fa-check"></i><b>1.2.7</b> Obteniendo ayuda</a></li>
<li class="chapter" data-level="1.2.8" data-path="intro.html"><a href="intro.html#lectura-de-datos"><i class="fa fa-check"></i><b>1.2.8</b> Lectura de datos</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#rstudio"><i class="fa fa-check"></i><b>1.3</b> RStudio</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="rls.html"><a href="rls.html"><i class="fa fa-check"></i><b>2</b> Regresión Lineal Simple</a>
<ul>
<li class="chapter" data-level="2.1" data-path="rls.html"><a href="rls.html#formulación-básica-del-modelo-de-rls"><i class="fa fa-check"></i><b>2.1</b> Formulación básica del modelo de RLS</a></li>
<li class="chapter" data-level="2.2" data-path="rls.html"><a href="rls.html#minimos"><i class="fa fa-check"></i><b>2.2</b> Estimación</a></li>
<li class="chapter" data-level="2.3" data-path="rls.html"><a href="rls.html#tabla-anova-y-medidas-de-desempeño"><i class="fa fa-check"></i><b>2.3</b> Tabla ANOVA y medidas de desempeño</a>
<ul>
<li><a href="rls.html#estimación-de-sigma2">Estimación de <span class="math inline">\(\sigma^2\)</span></a></li>
<li><a href="rls.html#inferencia-para-sigma2">Inferencia para <span class="math inline">\(\sigma^2\)</span></a></li>
<li><a href="rls.html#coeficiente-de-determinación-r2">Coeficiente de determinación <span class="math inline">\(R^2\)</span></a></li>
<li class="chapter" data-level="" data-path="rls.html"><a href="rls.html#validación-del-modelo-de-rls"><i class="fa fa-check"></i>Validación del modelo de RLS</a></li>
<li><a href="rls.html#inferencia-para-beta_0-y-beta_1">Inferencia para <span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span></a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="rls.html"><a href="rls.html#residuales"><i class="fa fa-check"></i><b>2.4</b> Análisis de Residuales</a>
<ul>
<li class="chapter" data-level="" data-path="rls.html"><a href="rls.html#validación-de-supuestos"><i class="fa fa-check"></i>Validación de Supuestos</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="rls.html"><a href="rls.html#predicción"><i class="fa fa-check"></i><b>2.5</b> Predicción</a>
<ul>
<li><a href="rls.html#intervalo-de-confianza-para-eyxx_0">Intervalo de confianza para <span class="math inline">\(E[Y|X=x_0]\)</span></a></li>
<li><a href="rls.html#intervalo-de-predicción-para-eyxx_0">Intervalo de predicción para <span class="math inline">\(E[Y|X=x_0]\)</span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="rlm.html"><a href="rlm.html"><i class="fa fa-check"></i><b>3</b> Regresión Lineal Múltiple</a>
<ul>
<li class="chapter" data-level="3.1" data-path="rlm.html"><a href="rlm.html#formulación-básica-del-modelo-de-rlm"><i class="fa fa-check"></i><b>3.1</b> Formulación básica del modelo de RLM</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="rlm.html"><a href="rlm.html#estimacion"><i class="fa fa-check"></i><b>3.1.1</b> Estimación</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="rlm.html"><a href="rlm.html#propiedades-de-los-estimadores-de-mathbfbeta"><i class="fa fa-check"></i><b>3.2</b> Propiedades de los estimadores de <span class="math inline">\({\mathbf{\beta}}\)</span></a></li>
<li class="chapter" data-level="3.3" data-path="rlm.html"><a href="rlm.html#estimación-de-sigma2-1"><i class="fa fa-check"></i><b>3.3</b> Estimación de <span class="math inline">\(\sigma^2\)</span></a></li>
<li class="chapter" data-level="3.4" data-path="rlm.html"><a href="rlm.html#inferencia-para-mathbfbeta"><i class="fa fa-check"></i><b>3.4</b> Inferencia para <span class="math inline">\(\mathbf{\beta}\)</span></a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="rlm.html"><a href="rlm.html#prueba-de-significancia-global"><i class="fa fa-check"></i><b>3.4.1</b> Prueba de significancia global</a></li>
<li class="chapter" data-level="3.4.2" data-path="rlm.html"><a href="rlm.html#prueba-de-significancia-marginal"><i class="fa fa-check"></i><b>3.4.2</b> Prueba de significancia marginal</a></li>
<li class="chapter" data-level="3.4.3" data-path="rlm.html"><a href="rlm.html#intervalos-de-confianza-para-beta_j"><i class="fa fa-check"></i><b>3.4.3</b> Intervalos de confianza para <span class="math inline">\(\beta_j\)</span></a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="rlm.html"><a href="rlm.html#inferencia-para-emathbfymathbfx_0"><i class="fa fa-check"></i><b>3.5</b> Inferencia para <span class="math inline">\(E[\mathbf{Y}|\mathbf{x}_0]\)</span></a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="rlm.html"><a href="rlm.html#intervalos-de-confianza-para-emathbfymathbfx_0"><i class="fa fa-check"></i><b>3.5.1</b> Intervalos de confianza para <span class="math inline">\(E[\mathbf{Y}|\mathbf{x}_0]\)</span></a></li>
<li class="chapter" data-level="3.5.2" data-path="rlm.html"><a href="rlm.html#intervalos-de-predicción-para-emathbfymathbfx_0"><i class="fa fa-check"></i><b>3.5.2</b> Intervalos de predicción para <span class="math inline">\(E[\mathbf{Y}|\mathbf{x}_0]\)</span></a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="rlm.html"><a href="rlm.html#análisis-de-residuales"><i class="fa fa-check"></i><b>3.6</b> Análisis de Residuales</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="rlm.html"><a href="rlm.html#validación-de-supuestos-1"><i class="fa fa-check"></i><b>3.6.1</b> Validación de supuestos</a></li>
<li class="chapter" data-level="3.6.2" data-path="rlm.html"><a href="rlm.html#identificación-de-outliers"><i class="fa fa-check"></i><b>3.6.2</b> Identificación de <em>outliers</em></a></li>
<li class="chapter" data-level="3.6.3" data-path="rlm.html"><a href="rlm.html#identificación-de-observaciones-influenciales"><i class="fa fa-check"></i><b>3.6.3</b> Identificación de observaciones influenciales</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="rlm.html"><a href="rlm.html#análisis-de-multicolinealidad"><i class="fa fa-check"></i><b>3.7</b> Análisis de Multicolinealidad</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="rlm.html"><a href="rlm.html#cómo-detectarla"><i class="fa fa-check"></i><b>3.7.1</b> Cómo detectarla?</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="rlm.html"><a href="rlm.html#selección-de-modelos"><i class="fa fa-check"></i><b>3.8</b> Selección de Modelos</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="rlm.html"><a href="rlm.html#método-de-todas-las-regresiones-posibles"><i class="fa fa-check"></i><b>3.8.1</b> Método de Todas las Regresiones Posibles</a></li>
<li class="chapter" data-level="3.8.2" data-path="rlm.html"><a href="rlm.html#selección-secuencial"><i class="fa fa-check"></i><b>3.8.2</b> Selección secuencial</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="glm.html"><a href="glm.html"><i class="fa fa-check"></i><b>4</b> Modelos de Regresión Avanzados</a>
<ul>
<li class="chapter" data-level="4.1" data-path="glm.html"><a href="glm.html#regresión-no-lineal"><i class="fa fa-check"></i><b>4.1</b> Regresión No Lineal</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="glm.html"><a href="glm.html#ejercicios"><i class="fa fa-check"></i><b>4.1.1</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="glm.html"><a href="glm.html#regresión-logística"><i class="fa fa-check"></i><b>4.2</b> Regresión Logística</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="glm.html"><a href="glm.html#ejercicios-1"><i class="fa fa-check"></i><b>4.2.1</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="glm.html"><a href="glm.html#regresión-poisson"><i class="fa fa-check"></i><b>4.3</b> Regresión Poisson</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="glm.html"><a href="glm.html#variaciones"><i class="fa fa-check"></i><b>4.3.1</b> Variaciones</a></li>
<li class="chapter" data-level="4.3.2" data-path="glm.html"><a href="glm.html#ejercicios-2"><i class="fa fa-check"></i><b>4.3.2</b> Ejercicios</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="series.html"><a href="series.html"><i class="fa fa-check"></i><b>5</b> Introducción a Series de Tiempo</a>
<ul>
<li class="chapter" data-level="5.1" data-path="series.html"><a href="series.html#qué-es-una-serie-de-tiempo"><i class="fa fa-check"></i><b>5.1</b> Qué es una Serie de Tiempo?</a></li>
<li class="chapter" data-level="5.2" data-path="series.html"><a href="series.html#definiciones-básicas"><i class="fa fa-check"></i><b>5.2</b> Definiciones básicas</a></li>
<li class="chapter" data-level="5.3" data-path="series.html"><a href="series.html#por-qué-y-para-qué"><i class="fa fa-check"></i><b>5.3</b> Por qué y para qué?</a></li>
<li class="chapter" data-level="5.4" data-path="series.html"><a href="series.html#modelos-básicos"><i class="fa fa-check"></i><b>5.4</b> Modelos básicos</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="series.html"><a href="series.html#método-de-descomposición"><i class="fa fa-check"></i><b>5.4.1</b> Método de Descomposición</a></li>
<li class="chapter" data-level="5.4.2" data-path="series.html"><a href="series.html#métodos-de-suavizamiento"><i class="fa fa-check"></i><b>5.4.2</b> Métodos de Suavizamiento</a></li>
<li class="chapter" data-level="5.4.3" data-path="series.html"><a href="series.html#metodología-box-jenkins"><i class="fa fa-check"></i><b>5.4.3</b> Metodología Box-Jenkins</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="series.html"><a href="series.html#validación-de-supuestos-2"><i class="fa fa-check"></i><b>5.5</b> Validación de supuestos</a></li>
<li class="chapter" data-level="5.6" data-path="series.html"><a href="series.html#pronósticos"><i class="fa fa-check"></i><b>5.6</b> Pronósticos</a></li>
<li class="chapter" data-level="5.7" data-path="series.html"><a href="series.html#ejercicios-3"><i class="fa fa-check"></i><b>5.7</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="enp.html"><a href="enp.html"><i class="fa fa-check"></i><b>6</b> Estadística No Paramétrica</a>
<ul>
<li class="chapter" data-level="6.1" data-path="enp.html"><a href="enp.html#por-qué-y-para-qué-1"><i class="fa fa-check"></i><b>6.1</b> Por qué y para qué?</a></li>
<li class="chapter" data-level="6.2" data-path="enp.html"><a href="enp.html#modelos-básicos-1"><i class="fa fa-check"></i><b>6.2</b> Modelos básicos</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="enp.html"><a href="enp.html#prueba-de-signos"><i class="fa fa-check"></i><b>6.2.1</b> Prueba de signos</a></li>
<li class="chapter" data-level="6.2.2" data-path="enp.html"><a href="enp.html#prueba-de-rangos-con-signos"><i class="fa fa-check"></i><b>6.2.2</b> Prueba de Rangos con Signos</a></li>
<li class="chapter" data-level="6.2.3" data-path="enp.html"><a href="enp.html#prueba-de-mann-whitney-wilcoxon"><i class="fa fa-check"></i><b>6.2.3</b> Prueba de Mann-Whitney-Wilcoxon</a></li>
<li class="chapter" data-level="6.2.4" data-path="enp.html"><a href="enp.html#prueba-de-kruskal-wallis"><i class="fa fa-check"></i><b>6.2.4</b> Prueba de Kruskal-Wallis</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="enp.html"><a href="enp.html#ejercicios-4"><i class="fa fa-check"></i><b>6.3</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="palabras-finales.html"><a href="palabras-finales.html"><i class="fa fa-check"></i><b>7</b> Palabras Finales</a></li>
<li class="chapter" data-level="" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i>Referencias</a></li>
<li class="divider"></li>
<li><a href="https://github.com/jivelez/book-adii" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Modelos de Regresión: Una aproximación práctica con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="rls" class="section level1" number="2">
<h1><span class="header-section-number">Capítulo 2</span> Regresión Lineal Simple</h1>
<p>Diariamente, en muchos procesos productivos se controlan las condiciones de operación de un sistema y es de interés determinar cómo una variable respuesta de cambia dependiendo dichas condiciones. Por ejemplo, en un proceso de embutido de cárnicos la cantidad de producto empacado (en gramos, por ejemplo) dependa de la velocidad y la temperatura a la que opere una máquina.</p>
<p>En la práctica, por supuesto, es fundamental</p>
<ol style="list-style-type: decimal">
<li>Entender la relación entre la cantidad de producto empacado, la velocidad y la temperatura de operación;</li>
<li>Garantizar que la cantidad de producto empacado cumpla con las especificaciones;</li>
<li>Determinar las condiciones óptimas de operación que minimizan los costos asociados y disminuyen considerablemente los desperdicios de producto.</li>
</ol>
<p>El Modelo de Regresión Lineal es ampliamente utilizado en la práctica ingenieril cuando, en un proceso productivo como el anterior, se quiere dar respuesta los numerales 1, 2 y 3. En un sentido menos amplio, los modelos de regresión lineal se utilizan para estudiar la relación entre una variable numérica, que denominamos <em>variable respuesta</em> <span class="math inline">\(Y\)</span>, y un conjunto de variables <em>controlables</em> de dicho proceso denotadas como <span class="math inline">\(X_1, X_2,\ldots, X_k\)</span>. Una vez entendemos dicha relación, es posible <em>predecir</em> futuros valores de la variable respuesta para valores <em>específicos y conocidos</em> de las variabes controlables.</p>

<div class="rmdnote">
Por <strong>variable controlable</strong> entendemos aquellas variables de proceso que pueden medirse fácilmente y se mantienen <em>fijas</em> durante la operación.
</div>
<p>Dependiendo del número de variables controlables, los modelos de Regresión Lineal pueden dividirse en <em>Modelo de Regresión Lineal Simple</em> (RLS) y <em>Modelo de Regresión Lineal Múltiple</em> (RLM).</p>
<ol style="list-style-type: decimal">
<li>Cuando se tiene <strong>sólo una</strong> variable controlable, digamos <span class="math inline">\(x\)</span>, hablamos de RLS.</li>
<li>Cuando se tienen <strong>más de una variable controlable</strong>, digamos <span class="math inline">\(x_1, x_2, \ldots, x_k\)</span>, hablamos de RLM. En el caso de proceso de embutidos, <span class="math inline">\(x_1 = \text{velocidad}\)</span> y <span class="math inline">\(x_2 = \text{temperatura}\)</span>.</li>
</ol>
<div id="formulación-básica-del-modelo-de-rls" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Formulación básica del modelo de RLS</h2>
<p>El modelo de RLS surge ante la necesidad de <em>predecir</em> una variable respuesta <span class="math inline">\(Y\)</span>, generalmente continua, como función de una variable <em>controlable</em> <span class="math inline">\(X\)</span>.</p>
<p>Matemáticamente el modelo puede expresarse como:</p>
<p><span class="math display">\[\begin{align} \label{mod1}
Y_i &amp;= \beta_0 + \beta_1X_i + \epsilon_i,\\ 
\epsilon_i &amp;\sim N(0, \sigma^2), \\
\sigma^2 &amp;= \text{constante}.
\end{align}\]</span></p>
<p>donde <span class="math inline">\((\beta_0, \beta_1, \sigma^2)\)</span> corresponden a los <strong>parámetros</strong> del modelo y <span class="math inline">\(\epsilon_i\)</span> es el error aleatorio para la observación <span class="math inline">\(i\)</span>. Los términos <span class="math inline">\((\beta_0, \beta_1)\)</span> corresponden a los <strong>coeficientes del modelo</strong>, mientras <span class="math inline">\(\sigma^2\)</span> es <strong>la varianza</strong>. En la práctica, se tiene o toma una muestra aleatoria de tamaño <span class="math inline">\(n\)</span> de una población o proceso de producción/servicios, y se quieren estimar, a partir de dicha muestra, los valores de <span class="math inline">\((\beta_0, \beta_1, \sigma^2\)</span>).</p>
<p>Consideremos un proceso donde se tienen registros de la <code>Resistencia</code>, en psi, y la <code>Edad</code>, en semanas, de varias soldaduras. Los datos pueden leerse en <code>R</code> como se muestra a continuación:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="rls.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="do">## lectura de datos en URL</span></span>
<span id="cb23-2"><a href="rls.html#cb23-2" aria-hidden="true" tabindex="-1"></a>file <span class="ot">&lt;-</span> <span class="st">&quot;https://www.dropbox.com/s/h4abseyfnvfwgxq/data_rls.txt?dl=1&quot;</span></span>
<span id="cb23-3"><a href="rls.html#cb23-3" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">file =</span> file, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb23-4"><a href="rls.html#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="rls.html#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="do">## primeras 6 filas de los datos</span></span>
<span id="cb23-6"><a href="rls.html#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(datos) </span></code></pre></div>
<pre><code>##   Resistencia Edad
## 1        10.9 18.7
## 2        10.6 19.1
## 3        13.4  9.3
## 4        10.7 17.5
## 5        13.0 14.6
## 6        13.1 12.8</code></pre>
<p>Con miras explorar si existe una relación entre la <code>Resistencia</code>y la <code>Edad</code> de la soldadura, existen dos estrategias.</p>

<div class="rmdwarning">
<p>En RLS, es posible establecer si existe una <em>posible</em> relación entre <span class="math inline">\(X\)</span> y <span class="math inline">\(Y\)</span> es</p>
<ol style="list-style-type: decimal">
<li>Construir un gráfico de dispersión.</li>
<li>Calculando el coeficiente de correlación lineal muestral;</li>
</ol>
</div>
<p>Para construir un gráfico de dispersión procedemos de la siguiente manera:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="rls.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="do">## gráfico de dispersión</span></span>
<span id="cb25-2"><a href="rls.html#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(ggplot2)</span>
<span id="cb25-3"><a href="rls.html#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x =</span> Edad, <span class="at">y =</span> Resistencia)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb25-4"><a href="rls.html#cb25-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-41-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Observe que, aparentemente, cuanto mayor sea la <code>Edad</code> de la soldadura <em>menor</em> será su <code>Resistencia</code>. Por lo tanto, podemos decir que la relación entre <code>Edad</code> y <code>Resistencia</code> es <em>inversamente proporcional</em>.</p>
<p>El <strong>coeficiente de correlación</strong> <span class="math inline">\(\rho\)</span> entre dos variables aleatorias <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> determina la <em>relación lineal</em> que existe entre ellas. A partir de una muestra de tamaño <span class="math inline">\(n\)</span>, dicho coeficiente puede calcularse como</p>
<p><span class="math display">\[\begin{eqnarray}
\hat{\rho}_{XY} &amp;=&amp; \frac{\text{Cov}(X,Y)}{\sigma_X \sigma_Y} \\\nonumber
                &amp;=&amp; \frac{\sum_{i=1}^n{(x_i-\bar{x})(y_i-\bar{y})}}{\sqrt{\sum_{i=1}^n{(x_i-\bar{x})^2}\sum_{i=1}^n{(y_i-\bar{y})^2}}}
\end{eqnarray}\]</span></p>
<p>donde</p>
<p><span class="math display">\[\begin{eqnarray}
\bar{x} &amp;=&amp; \frac{\sum_{i=1}^n{x_i}}{n} \\\nonumber
\bar{y} &amp;=&amp; \frac{\sum_{i=1}^n{y_i}}{n}.
\end{eqnarray}\]</span></p>

<div class="rmdwarning">
<p>El coeficiente de correlación muestral <span class="math inline">\(-1\leq \hat{\rho}_{XY} \leq 1\)</span> determina la relación <strong>lineal</strong> entre las variables <span class="math inline">\(X\)</span> y <span class="math inline">\(Y\)</span>.</p>
<ul>
<li><span class="math inline">\(\hat{\rho}_{XY} \approx -1\)</span> indica <span class="math inline">\(X\)</span> y <span class="math inline">\(Y\)</span> tienen una <em>relación lineal inversa</em>, es decir, que cuando <span class="math inline">\(X\)</span> aumenta, la variable <span class="math inline">\(Y\)</span> disminuye.</li>
<li><span class="math inline">\(\hat{\rho}_{XY} \approx 0\)</span> indica que <strong>no existe</strong> una relación lineal entre <span class="math inline">\(X\)</span> y <span class="math inline">\(Y\)</span>. Sin embargo, este resultado no es suficiente para descartar que exista otro tipo de relación (por ejemplo cuadrática o cúbica) entre las dos variables.</li>
<li><span class="math inline">\(\hat{\rho}_{XY} \approx 1\)</span> indica <span class="math inline">\(X\)</span> y <span class="math inline">\(Y\)</span> tienen una <em>relación lineal positiva</em>, es decir, que cuando <span class="math inline">\(X\)</span> aumenta, la variable <span class="math inline">\(Y\)</span> también.
</div></li>
</ul>
<p>Con los datos de soldaduras se tendría que:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="rls.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="do">## coeficiente de correlación</span></span>
<span id="cb26-2"><a href="rls.html#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(datos, <span class="fu">cor</span>(Edad, Resistencia))</span></code></pre></div>
<pre><code>## [1] -0.8827718</code></pre>
<p>Por lo tanto, concluimos que la relación entre la <code>Edad</code> de la soldadura y su <code>Resistencia</code> es <em>inversamente proporcional</em>.</p>
</div>
<div id="minimos" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Estimación</h2>
<p>Para estimar el modelo de RLS, se requiere una muestra aleatoria de tamaño <span class="math inline">\(n\)</span> de una población. Esta muestra puede corresponder a observaciones específicas de un proceso de producción o servicios donde se controla una variable <span class="math inline">\(X\)</span> y se registra una variable respuesta <span class="math inline">\(Y\)</span>. Por lo general, los datos para <span class="math inline">\(n\)</span> unidades experimentales de dicho proceso están constituidos por los pares <span class="math display">\[(x_1,y_1),(x_2,y_2),(x_3, y_3),\ldots,(x_n,y_n).\]</span></p>
<p>En nuestro ejemplo, los datos están organizados de la siguiente forma:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="rls.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="do">## muestra los primeros 10 pares de datos</span></span>
<span id="cb28-2"><a href="rls.html#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(datos, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>##    Resistencia Edad
## 1         10.9 18.7
## 2         10.6 19.1
## 3         13.4  9.3
## 4         10.7 17.5
## 5         13.0 14.6
## 6         13.1 12.8
## 7         12.1 16.0
## 8         14.3  7.0
## 9         11.9 14.9
## 10        11.1 15.6</code></pre>
<p>Así, los pares <span class="math inline">\((x_1,y_1)\)</span> y <span class="math inline">\((x_5, y_5)\)</span> corresponden a <span class="math inline">\((18.7, 10.9)\)</span> y <span class="math inline">\((14.6, 13.0)\)</span>, respectivamente.</p>
<p>Para determinar el tamaño de la muestra, hacemos</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="rls.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="do">## número total de observaciones</span></span>
<span id="cb30-2"><a href="rls.html#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">NROW</span>(datos) </span></code></pre></div>
<pre><code>## [1] 100</code></pre>
<!-- Una forma de realizar una primera aproximación descriptiva a los datos que tenemos es a partir de la función `summary` del paquete `skimr` \index{skimr}[@skimr]: -->
<!-- ```{r, message=FALSE} -->
<!-- require(skimr) -->
<!-- skim_without_charts(datos) -->
<!-- ``` -->
<!-- Etos resultados indican que: -->
<!-- 1. El objeto `datos` es un `data.frame` con 100 filas y  2 columnas; -->
<!-- 2. La `Resistencia` promedio de las soldaduras es 12.6, la desviación estándar de 1.25, con valores mínimos y máximos de 10.6 y 16.3, respectivamente; -->
<!-- 3. La `Edad` de las soldaduras varía entre 5 y 19.8 años, con un promedio de 12.9 años y una desviación estándar de 4.53 años; -->
<!-- 4. La disribución de la `Resistencia` es sesgada a la izquierda, mientras la distribución de la `Edad` es sesgada a la derecha. -->
<p>Usualmente, los parámetros <span class="math inline">\((\beta_0, \beta_1,\sigma^2)\)</span> el modelo de RLS puede estimarse utilizando el método de <a href="rls.html#minimos">mínimos cuadrados</a>. La idea fundamental es minizar la expresión</p>
<p><span class="math display">\[\begin{eqnarray*}
L &amp;=&amp;\sum_{i=1}^n\epsilon_i^2 = \sum_{i=1}^n(Y_i-\beta_0-\beta_1X_i)^2.
\end{eqnarray*}\]</span></p>
<p>Para encontrar los estimadores de <span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span> derivamos parcialmente e igualamos a cero las expresiones resultantes, esto es</p>
<p><span class="math display">\[\frac{\partial L}{\partial \beta_0}=0, \hspace{1cm} \frac{\partial L}{\partial \beta_1}=0.\]</span></p>
<p>Los estimadores <span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span> están dados por</p>
<p><span class="math display">\[\begin{align}
\widehat{\beta}_0&amp;=\overline{Y}-\widehat{\beta}_1\overline{X}, \\ \widehat{\beta}_1&amp;=\frac{S_{xy}}{S_{xx}}
\end{align}\]</span></p>
<p>donde</p>
<p><span class="math display">\[
S_{xx} = \sum_{i=1}^n(x_i-\bar{x})^2 \quad\text{y}\quad
S_{xy} = \sum_{i=1}^n(x_i-\bar{x})(y_i-\bar{y}).
\]</span></p>

<div class="rmdtip">
En la práctica, <span class="math inline">\(\widehat{\beta}_1\)</span> se interpreta como <strong>el cambio unitario</strong> sobre el valor esperado de <span class="math inline">\(Y\)</span>, <span class="math inline">\(E[Y|X]\)</span>, por cada cambio unitario del <strong>factor controlable</strong> <span class="math inline">\(X\)</span>.
</div>
<p>Por otro lado,</p>
<p><span class="math display">\[\begin{align}
\hat{\sigma}^2 &amp;= \frac{L}{n-2} \\ &amp;=\frac{1}{n-2}\sum_{i=1}^n\hat{\epsilon}_i^2 \\ &amp;=\frac{1}{n-2}\sum_{i=1}^n(y_i-\hat{y}_i)^2 \\ &amp;=\frac{1}{n-2}\sum_{i=1}^n(y_i-\hat{\beta}_0-\hat{\beta}_1X_i)^2 \\
&amp;=\frac{SSE}{n-2} \\
&amp;= MSE 
\end{align}\]</span></p>
<p>donde el <span class="math inline">\(SSE\)</span> corresponde a la suma de cuadrados del error, y <span class="math inline">\(MSE\)</span> es el <em>Mean Squared Error</em>.</p>
<p>Finalmente, el modelo de RLS estimado es</p>
<p><span class="math display">\[\begin{align} 
\widehat{Y}_i &amp;= \hat{\beta}_0 + \hat{\beta}_1X_i,\\ 
\epsilon_i &amp;\sim N(0, \hat{\sigma}^2), \\
\hat{\sigma}^2 &amp;= \text{constante}.
\end{align}\]</span></p>
<p>Otra forma de escribirlo es</p>
<p><span class="math display">\[\begin{align} 
\widehat{Y}_i &amp;\sim N(\hat{\mu}_i, \hat{\sigma}^2), \\
\hat{\mu}_i &amp;= \hat{\beta}_0 + \hat{\beta}_1X_i.
\end{align}\]</span></p>
<p>A partir del modelo ajustado es posible <strong>predicir el valor esperado</strong> de <span class="math inline">\(Y\)</span> para valores <strong>conocidos</strong> de <span class="math inline">\(X\)</span>, es decir, calcular <span class="math inline">\(\widehat{E[Y|X=x_0]}\)</span>, donde <span class="math inline">\(x_0\)</span> es un <strong>valor conocido</strong> del factor controlable <span class="math inline">\(X\)</span>. Adicionalmente, podemos calcular intervalos de confianza e intervalos de predicción para <span class="math inline">\({E[Y|X=x_0]}\)</span>.</p>
<p>Observe que para un valor específico de <span class="math inline">\(X\)</span>, digamos <span class="math inline">\(x_i\)</span>, se tiene el valor correspondiente de <span class="math inline">\(Y\)</span> es <span class="math inline">\(y_i\)</span>. En otras palabras, la <span class="math inline">\(i\)</span>-ésima unidad experimental se produjo cuando <span class="math inline">\(X = x_i\)</span> y que, bajo estas condiciones, se obtuvo que <span class="math inline">\(Y = y_i\)</span>.</p>
<p>En <code>R</code> la función clave paara ajustar modelos de RLS es <code>lm</code>. Para mayor información, puede consultar la ayuda de la función escribiendo <code>?lm</code> en la consola, o en la <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/lm.html">página</a> oficial.</p>
<p>En general, la sintaxis es</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="rls.html#cb32-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> datos)</span></code></pre></div>
<p>donde <code>y</code> es la variable respuesta, <code>x</code> es el factor controlable o variable independiente y <code>datos</code> es el objeto en <code>R</code> que contiene los datos con los que estamos trabajando.</p>
<p>Para los datos de las soldaduras se tiene que:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="rls.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="do">## ajuste del modelo de RLS</span></span>
<span id="cb33-2"><a href="rls.html#cb33-2" aria-hidden="true" tabindex="-1"></a>(modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(Resistencia <span class="sc">~</span> Edad, <span class="at">data =</span> datos))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Resistencia ~ Edad, data = datos)
## 
## Coefficients:
## (Intercept)         Edad  
##     15.7427      -0.2438</code></pre>
<p>Los resultados indican que <span class="math inline">\(\widehat{\beta}_0 = 15.74\)</span> y <span class="math inline">\(\widehat{\beta}_1 = -0.244\)</span>. Por lo tanto, el modelo ajustado puede escribirse como:</p>
<p><span class="math display">\[\begin{align}
\widehat{\text{Resistencia}}_i &amp;= 15.74 -0.244\,\text{Edad}_i ,\\ 
\epsilon_i &amp;\sim N(0, \sigma^2), \\
\sigma^2 &amp;= \text{constante}.
\end{align}\]</span></p>

<div class="rmdnote">
<p>Cómo interpretamos <span class="math inline">\(\widehat{\beta}_0\)</span> y <span class="math inline">\(\widehat{\beta}_1\)</span>?</p>
<ol style="list-style-type: decimal">
<li>Se espera que, por cada semana que transcurre, la resistencia de la soldadura disminuya <span class="math inline">\(0.244\)</span> psi.</li>
<li>Una soldadura <em>nueva</em> <span class="math inline">\((\text{Edad} = 0)\)</span> tiene una resistencia promedio de <span class="math inline">\(15.74\)</span> psi
</div></li>
</ol>
<p>Observe que aún no tenemos el valor estimado de <span class="math inline">\(\sigma\)</span>. Este parámetro del modelo de RLS puede obtenerse como el <span class="math inline">\(MSE\)</span> de la tabla de análisis de varianza o Tabla ANOVA, que describiremos a continuación.</p>
</div>
<div id="tabla-anova-y-medidas-de-desempeño" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Tabla ANOVA y medidas de desempeño</h2>
<p>La Tabla ANOVA es útil para</p>
<ol style="list-style-type: decimal">
<li>estimar la varianza del modelo de RLS, <span class="math inline">\(\sigma^2\)</span>;</li>
<li>calcular el coeficiente de determinación <span class="math inline">\(R^2\)</span>;</li>
<li>verificar la bondad de ajuste del modelo.</li>
</ol>
<p>En el modelo de RLS, la <strong>varianza</strong> total de la respuesta puede descomponerse como</p>
<p><span class="math display">\[SST = SSR + SSE\]</span>
donde</p>
<p><span class="math display">\[\begin{align} 
SSR &amp;= \text{ varianza atribuible al factor controlable } x\\
SSE &amp;= \text{ varianza atribuible a factores no controlables} 
\end{align}\]</span></p>

<div class="rmdwarning">
Usualmente, el término <span class="math inline">\(SSR\)</span> se refiere a cuánto de la varianza observada en <span class="math inline">\(Y\)</span> puede ser <strong>explicada por el factor controlable</strong> <span class="math inline">\(x\)</span>. Por otro lado, el término <span class="math inline">\(SSE\)</span> corresponde a cuánto de la varianza de <span class="math inline">\(Y\)</span> puede explicarse a través de otros factores que, desafortunadamente, <strong>no fueron controlados ni medidos</strong> durante la toma de la muestra. Si el modelo es suficientemente bueno, <span class="math inline">\(SSE\rightarrow 0\)</span>.
</div>
<p>A partir de la muestra,</p>
<p><span class="math display">\[\begin{align}
SST &amp;= \sum_{i=1}^n(y_i-\bar{y})^2, \\
SSR &amp;= \sum_{i=1}^n(\hat{y}_i-\bar{y})^2=\widehat{\beta}_1S_{xy}, \\ 
SSE &amp;= L = \sum_{i=1}^n\widehat{\epsilon}_i^2 = \sum_{i=1}^n(y_i-\hat{y}_i)^2 \\
\widehat{y}_i &amp;= \widehat{\beta}_0-\widehat{\beta}_1X_i \end{align}\]</span></p>
<div id="estimación-de-sigma2" class="section level3 unnumbered">
<h3>Estimación de <span class="math inline">\(\sigma^2\)</span></h3>
<p>A partir de los resultados una vez es estima el modelo,</p>
<p><span class="math display">\[\widehat{\sigma}^2 = \frac{L}{n-2} = \frac{SSE}{n-2} = MSE\]</span></p>
<p>El término <span class="math inline">\(MSE\)</span> se obtiene de la Tabla ANOVA. Al igual a como ocurre con el <span class="math inline">\(SSE\)</span>, el <span class="math inline">\(MSE\rightarrow 0\)</span> para un modelo de RLS <strong>ideal</strong>. Aunque esto es deseable, es difícilmente observable en la práctica debido a las innumerables fuentes de variabilidad de los procesos de producción y de servicios.</p>
<p>En <code>R</code>, el valor de <em>Residual Standard Error</em>, <span class="math inline">\(RSE\)</span>, calculado como <span class="math inline">\(RSE = \sqrt{MSE} = \hat{\sigma}\)</span> puede obtenerse como:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="rls.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="do">## estimación de sigma</span></span>
<span id="cb35-2"><a href="rls.html#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)<span class="sc">$</span>sigma</span></code></pre></div>
<pre><code>## [1] 0.5908683</code></pre>
<p>A partir de etse resultado se concluye que <span class="math inline">\(\hat{\sigma} = 0.591\)</span>. Por lo tanto, <span class="math inline">\(MSE = 0.591^2 = 0.349\)</span>. Finalmente, el modelo ajustado puede expresarse como</p>
<p><span class="math display">\[\begin{align}
\widehat{\text{Resistencia}}_i &amp;\sim N(\hat{\mu}_i, \hat{\sigma}^2),\\ \hat{\mu}_i &amp;\sim 15.743 - 0.244\,\text{Edad}, \\
\hat{\sigma}^2 &amp;= 0.591^2 = 0.349.
\end{align}\]</span></p>
</div>
<div id="inferencia-para-sigma2" class="section level3 unnumbered">
<h3>Inferencia para <span class="math inline">\(\sigma^2\)</span></h3>
<p>A partir <span class="math inline">\(\widehat{\sigma}^2\)</span> es posible probar si</p>
<p><span class="math display">\[\begin{align}
H_0: \sigma^2 = \sigma^2_0 \\
H_1: \sigma^2 \neq \sigma^2_0
\end{align}\]</span></p>
<p>donde <span class="math inline">\(\sigma^2_0 &gt; 0\)</span> es un valor específico para <span class="math inline">\(\sigma^2\)</span>.</p>
<p>El resultado básico es</p>
<p><span class="math display">\[\frac{(n-2)\,\widehat{\sigma}^2}{\sigma^2}\sim \chi^2_{n-2} \]</span>
Así, un intervalo de confianza del <span class="math inline">\((1-\alpha)100\%\)</span> para <span class="math inline">\(\sigma^2\)</span> está dado por:</p>
<p><span class="math display">\[\sigma^2 \in (a, b)\]</span>
donde</p>
<p><span class="math display">\[a = \frac{(n-2)\,\widehat{\sigma}^2}{\chi^2_{1-\alpha/2,n-2}}, \quad \quad b = \frac{(n-2)\widehat{\sigma}^2}{\chi^2_{\alpha/2,n-2}}
\]</span></p>
<p>Finalmente, diremos que <span class="math inline">\(\sigma^2 \neq \sigma^2_0\)</span> si el valor <span class="math inline">\(\sigma^2_0\)</span> <strong>no se encuentra</strong> en el intervalo <span class="math inline">\((a,b)\)</span>.</p>
<p>En <code>R</code> todo este procedimiento puede hacerse de la siguiente manera:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="rls.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="do">## intervalo de confianza para sigma^2</span></span>
<span id="cb37-2"><a href="rls.html#cb37-2" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb37-3"><a href="rls.html#cb37-3" aria-hidden="true" tabindex="-1"></a>resultados <span class="ot">&lt;-</span> <span class="fu">summary</span>(modelo)</span>
<span id="cb37-4"><a href="rls.html#cb37-4" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> resultados<span class="sc">$</span>sigma</span>
<span id="cb37-5"><a href="rls.html#cb37-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> resultados<span class="sc">$</span>df[<span class="dv">2</span>]</span>
<span id="cb37-6"><a href="rls.html#cb37-6" aria-hidden="true" tabindex="-1"></a>upper_limit <span class="ot">&lt;-</span> df<span class="sc">*</span>sigma<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="fu">qchisq</span>(alpha<span class="sc">/</span><span class="dv">2</span>, df)</span>
<span id="cb37-7"><a href="rls.html#cb37-7" aria-hidden="true" tabindex="-1"></a>lower_limit <span class="ot">&lt;-</span> df<span class="sc">*</span>sigma<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="fu">qchisq</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>, df)</span>
<span id="cb37-8"><a href="rls.html#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">lower_limit =</span> lower_limit, <span class="at">sigma2_hat =</span>sigma<span class="sc">^</span><span class="dv">2</span>, <span class="at">upper_limit =</span> upper_limit)</span></code></pre></div>
<pre><code>## lower_limit  sigma2_hat upper_limit 
##   0.2688068   0.3491253   0.4719150</code></pre>
<p>Finalmente, con una confianza del 95%, <span class="math inline">\(\sigma^2 \in(0.269, 0.472)\)</span>. Ahora, como el valor <span class="math inline">\(0\)</span> <strong>no</strong> se encuentra en el intervalo de confianza, podemos afirmar que <span class="math inline">\(\sigma^2 &gt; 0\)</span> a nivel poblacional.</p>
<p>Para obtener un intervalo de confianza del 95% para <span class="math inline">\(\sigma\)</span>, basta calcular la raíz cuadrada de estos límites. Por lo tanto, <span class="math inline">\(\sigma \in(0.519, 0.687)\)</span>.</p>
</div>
<div id="coeficiente-de-determinación-r2" class="section level3 unnumbered">
<h3>Coeficiente de determinación <span class="math inline">\(R^2\)</span></h3>
<p>En el modelo de RLS, una de las medidas más utilizadas para evaluar su desempeño o ajuste es el coeficiente de determinación <span class="math inline">\(R^2\)</span>. Matemáticamente, el <span class="math inline">\(R^2\)</span> puede calcularse como</p>
<p><span class="math display">\[R^2 = \widehat{\rho}_{XY}^2,\]</span></p>
<p>donde <span class="math inline">\(\widehat{\rho}_{XY}\)</span> es el coeficiente de correlación muestral entre <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span>, es un indicador de la calidad del modelo. En nuestro caso, una forma de hacerlo en <code>R</code> es</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="rls.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="do">## coeficiente de determinación</span></span>
<span id="cb39-2"><a href="rls.html#cb39-2" aria-hidden="true" tabindex="-1"></a>rho_est <span class="ot">&lt;-</span> <span class="fu">with</span>(datos, <span class="fu">cor</span>(Resistencia, Edad))</span>
<span id="cb39-3"><a href="rls.html#cb39-3" aria-hidden="true" tabindex="-1"></a>rho_est<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 0.7792861</code></pre>

<div class="rmdtip">
En la práctica, el <span class="math inline">\(R^2\)</span> puede interpretarse como <strong>el porcentaje de variabilidad total</strong> de la respuesta <span class="math inline">\(Y\)</span> que puede ser explicado por el modelo de RLS.
</div>
<p>Utilizando el objeto en <code>R</code> que contiene el modelo ajustado, podemos hacer</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="rls.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="do">## obtención del R^2 a partir de un objeto lm</span></span>
<span id="cb41-2"><a href="rls.html#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)<span class="sc">$</span>r.squared    </span></code></pre></div>
<pre><code>## [1] 0.7792861</code></pre>
<p>para obtener el coeficiente de determinación. Por lo tanto, podemos concluir, con base en nuestro modelo estimado de RLS, que la <code>Edad</code> de la soldadura explica alrededor del 78% de la varabilidad total de la <code>Resistencia</code>.</p>
<p>A partir de esta definición y los valores de <span class="math inline">\(SST\)</span>, <span class="math inline">\(SSR\)</span> y <span class="math inline">\(SSE\)</span> es fácil llegar a que</p>
<p><span class="math display">\[R^2 = 1-\frac{SSE}{SST}\]</span>
Técnicamente, <span class="math inline">\(0\leq R^2 \leq 1\)</span>, donde <span class="math inline">\(R^2 \rightarrow 0\)</span> y <span class="math inline">\(R^2 \rightarrow 1\)</span> representan modelos de RLS con desempeños deficientes e ideales, respectivamente. Sin embargo, en el Capítulo <a href="rlm.html#rlm">3</a> estudiaremos otras medidas que nos permiten determinar si nuestro modelo es lo suficientemente bueno. Al final, el objetivo es seleccionar <strong>el mejor modelo</strong> de regresión que nos permite explicar, correctamente, una variable respuesta de interés en función de una o más variables explicativas o controlables.</p>
</div>
<div id="validación-del-modelo-de-rls" class="section level3 unnumbered">
<h3>Validación del modelo de RLS</h3>
<p>Al utilizar RLS queremos estar seguros de que el modelo ajustado es <strong>considerablemente mejor</strong> que no tener dicho modelo. Esto equivale a determinar si la contribución del factor controlable <span class="math inline">\(X\)</span> para predecir <span class="math inline">\(E[Y|X=x_0]\)</span> es sustancial. Formalmente, esto equivale a realizar una <strong>prueba de significancia global</strong>.</p>

<div class="rmdtip">
<p>La prueba de significancia global puede realizarse de dos maneras en RLS:</p>
<ol style="list-style-type: decimal">
<li>Utilizando los resultados de la Tabla ANOVA;</li>
<li>A través de un procedimiento de pruebas de hipótesis basado en la distribución <span class="math inline">\(t\)</span> de Student.
</div></li>
</ol>
<p>En términos generales, la prueba de significancia global equivale a probar</p>
<p><span class="math display">\[
\begin{split}
&amp;H_0: \beta_1 = 0 \\
&amp;H_A: \beta_1 \neq0 
\end{split}
\]</span></p>
<p>Cuando utilizamos <strong>la Tabla ANOVA</strong>, el estadístico de prueba es</p>
<p><span class="math display">\[F_\text{calculado} = \frac{MSR}{MSE}  \sim F_{1, n-2}\]</span>
donde <span class="math inline">\(F_{1, n-2}\)</span> corresponde a la distribución <span class="math inline">\(F\)</span> con <span class="math inline">\(1\)</span> grado de libertad en el numerador y <span class="math inline">\(n-2\)</span> grados de libertad en el denominador.</p>

<div class="rmdtip">
<p>El estadístico <span class="math inline">\(F_\text{calculado}\)</span> contrasta qué tanto de la varianza de <span class="math inline">\(Y\)</span> puede explicarse con el factor controlable <span class="math inline">\(X\)</span> versus los factores incontrolables del proceso.</p>
<ul>
<li><span class="math inline">\(F_\text{calculado} &lt;&lt;&lt; 1\)</span> indica que los <strong>factores incontrolables</strong> explican más que el <strong>factor controlable</strong> <span class="math inline">\(X\)</span>. Si este fuera el caso, deberíamos explorar otro factor <span class="math inline">\(X\)</span> para explicar <span class="math inline">\(Y\)</span>.</li>
<li>Cuando <span class="math inline">\(F_\text{calculado} \approx 1\)</span>, la varianza de <span class="math inline">\(Y\)</span> explicada por el <strong>factor controlable</strong> y los <strong>factores incontrolables</strong> es similar. En esta situación, lo mejor es explorar otro factor <span class="math inline">\(X\)</span> para explicar <span class="math inline">\(Y\)</span>.</li>
<li>Cuando <span class="math inline">\(F_\text{calculado} &gt;&gt;&gt; 1\)</span> concluimos que la variabilidad de la respuesta puede ser explicada mayormente por el <strong>factor controlable</strong> que por aquellos **factores incontrolables*. Este es el caso ideal.
</div></li>
</ul>
<p>Para un nivel de significancia <span class="math inline">\(\alpha \in (0,1)\)</span>, rechazamos <span class="math inline">\(H_0\)</span> si</p>
<ol style="list-style-type: decimal">
<li><p><span class="math inline">\(F_\text{calculado} &gt; F_{1-\alpha,1,n-1}\)</span>, donde <span class="math inline">\(F_{\alpha/2,1,n-2}\)</span> es el percentil <span class="math inline">\(1-\alpha\)</span> de una distribución <span class="math inline">\(F\)</span> con 1 y <span class="math inline">\(n-2\)</span> grados de libertad. En <code>R</code>, estos percentiles pueden calcularse utilizando la función <code>qf</code>. Por ejemplo, <span class="math inline">\(F_{0.95,1,98}\)</span> es 3.94 y se obtiene como <code>qf(0.95, 1, 98)</code>.</p></li>
<li><p>El valor <span class="math inline">\(p\)</span>, calculado como <span class="math inline">\(p=P(F_{1,n-1}&gt;F_\text{calculado})\)</span>, es <strong>menor</strong> que <span class="math inline">\(\alpha\)</span>. Por ejemplo, si <span class="math inline">\(F_\text{calculado} = 7.34\)</span>, el valor <span class="math inline">\(p\)</span> para <span class="math inline">\(n=49\)</span> será 0.009. Este valor se obtiene con la función <code>pf()</code> haciendo <code>pf(7.34, 1, 49, lower.tail = FALSE)</code></p></li>
</ol>
<p>La prueba de significancia global se realiza de manera automática cuando empleamos usamos <code>summary(modelo)</code>. La parte relevante de los resultados corresponde a la <em>última línea</em> de la salida del <code>R</code>, es decir, a</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="rls.html#cb43-1" aria-hidden="true" tabindex="-1"></a>F<span class="sc">-</span>statistic<span class="sc">:</span>   <span class="dv">346</span> on <span class="dv">1</span> and <span class="dv">98</span> DF,  p<span class="sc">-</span>value<span class="sc">:</span> <span class="er">&lt;</span> <span class="fl">2.2e-16</span></span></code></pre></div>
<p>En este caso, <code>F-statistic</code> corresponde al estadístico de prueba <span class="math inline">\(F_\text{calculado}\)</span>, y los valores <code>1</code> y <code>98</code> a los grados de libertad del <span class="math inline">\(MSR\)</span> y <span class="math inline">\(MSE\)</span>, respectivamente. Finalmente, el valor <span class="math inline">\(p\)</span> es <span class="math inline">\(p=2.2\times10^{16}\)</span>, por lo que <strong>rechazamos</strong> <span class="math inline">\(H_0\)</span> y concluimos que incluir el modelo de RLS que incluye la <code>Edad</code> para explicar la <code>Resistencia</code> de una soldadura es mejor que no tener un modelo de sólo intercepto, es decir, un modelo que no incluye ningún factor controlable que probablemente modifique los valores de dicha <code>Resistencia</code>.</p>
<p>Cuando utilizamos <strong>la distribución <span class="math inline">\(t\)</span> de Student</strong>, podemos probar</p>
<p><span class="math display">\[
\begin{split}
&amp;H_0: \beta_1 = 0 \\
&amp;H_A: \beta_1 \neq0 
\end{split}
\]</span></p>
<p>A partir de las propiedades de los coeficientes estimados <span class="math inline">\((\widehat{\beta}_0,\widehat{\beta}_1)\)</span> y bajo condiciones de regularidad, es fácil llegar a que</p>
<p><span class="math display">\[\begin{align}
\widehat{\beta}_0 \sim N(\beta_0, \widehat{\sigma}_{\widehat{\beta}_0}^2) \\
\widehat{\beta}_1 \sim N(\beta_1, \widehat{\sigma}_{\widehat{\beta}_1}^2)
\end{align}\]</span></p>
<p>donde</p>
<p><span class="math display">\[\begin{align}
\widehat{\sigma}_{\widehat{\beta}_0}^2 &amp;= \sqrt{\hat{\sigma}^2\left(\frac{1}{n}+\frac{\bar{x}}{SS_x}\right)} \\
\widehat{\sigma}_{\widehat{\beta}_1}^2 &amp;=\sqrt{\frac{\hat{\sigma}^2}{SS_x}}
\end{align}\]</span></p>
<p>Así, el estadístico de prueba será</p>
<p><span class="math display">\[t_{\text{calculado}} = \frac{\hat{\beta}_1}{\widehat{\sigma}_{\widehat{\beta}_1}}\sim t_{n-2}\]</span></p>
<p>donde <span class="math inline">\(t_{n-2}\)</span> corresponde a la distribución <span class="math inline">\(t\)</span> con <span class="math inline">\(n-2\)</span> grados de libertad. Bajo <span class="math inline">\(H_0\)</span>, <span class="math inline">\(t_{\text{calculado}} \sim t_{n-2}\)</span>. Para un nivel de significancia <span class="math inline">\(\alpha \in (0,1)\)</span>, rechazamos <span class="math inline">\(H_0\)</span> si</p>
<ol style="list-style-type: decimal">
<li><p><span class="math inline">\(|t_\text{calculado}| &gt; t_{1-\alpha/2, n-2}\)</span>, donde <span class="math inline">\(t_{1-\alpha/2, n-2}\)</span> es el percentil <span class="math inline">\(1-\alpha/2\)</span> de una distribución <span class="math inline">\(t\)</span> con <span class="math inline">\(n-2\)</span> grados de libertad. En <code>R</code>, estos percentiles pueden calcularse utilizando la función <code>qt</code>. Por ejemplo, <span class="math inline">\(t_{0.95,98}\)</span> es 1.66 y se obtiene como <code>qt(0.95, 98)</code>.</p></li>
<li><p>El valor <span class="math inline">\(p\)</span>, calculado como <span class="math inline">\(p=2\,P(t_{n-2} &gt; |t_\text{calculado}|\)</span>, es <strong>menor</strong> que <span class="math inline">\(\alpha\)</span>. Por ejemplo, si <span class="math inline">\(t_\text{calculado} = 2.54\)</span> cuando <span class="math inline">\(n=60\)</span>, el valor <span class="math inline">\(p\)</span> será 0.014. Para calcularlo, usamos <code>2*pt(abs(2.54), 58, lower.tail = FALSE)</code> en <code>R</code>.</p></li>
</ol>

<div class="rmdtip">
Cuando <span class="math inline">\(n-2 &gt; 30\)</span>, podemos aproximar la distribución <span class="math inline">\(t_{n-2}\)</span> a la distribución Normal estándar. En <code>R</code>, utilizaríamos la <code>pnorm()</code> en lugar de <code>pt()</code>. Para más detalles, escriba <code>?pnorm</code> en la consola del <code>R</code>.
</div>
</div>
<div id="inferencia-para-beta_0-y-beta_1" class="section level3 unnumbered">
<h3>Inferencia para <span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span></h3>
<p>A partir de las distribuciones muestrales de <span class="math inline">\(\widehat{\beta}_0\)</span> y <span class="math inline">\(\widehat{\beta}_1\)</span> es posible realizar <strong>inferencia</strong> sobre <span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span>. Este trabajo inferencial puede hacerse a través de:</p>
<ol style="list-style-type: decimal">
<li>Pruebas de hipótesis</li>
<li>Intervalos de confianza</li>
</ol>
<p>Cuando utilizamos <strong>pruebas de hipótesis</strong>, se prueban</p>
<ul>
<li><p><span class="math inline">\(H_0:\beta_0 = 0\)</span> vs. <span class="math inline">\(H_1:\beta_0 \neq 0\)</span> usando el estadístico de prueba
<span class="math display">\[t_{\text{calc}} = \frac{\hat{\beta}_0-0}{\widehat{\sigma}_{\widehat{\beta}_0}}\]</span></p></li>
<li><p><span class="math inline">\(H_0:\beta_1 = 0\)</span> vs. <span class="math inline">\(H_1:\beta_1 \neq 0\)</span> usando el estadístico
<span class="math display">\[t_{\text{calc}} = \frac{\hat{\beta}_1-0}{\widehat{\sigma}_{\widehat{\beta}_1}}\]</span></p></li>
</ul>
<p>y, en cualquiera de los dos casos, rechazamos <span class="math inline">\(H_0\)</span> si <span class="math inline">\(|t_{\text{calculado}}| &gt; t_{1-\alpha/2,n-2}\)</span>.</p>
<p>Los <strong>intervalos de confianza</strong> del <span class="math inline">\((1-\alpha)100\%\)</span> para los coeficientes de represión serán</p>
<p><span class="math display">\[\begin{align}
{\beta}_0 \in (\hat{\beta}_0 - t_{\alpha/2,n-2}\,\widehat{\sigma}_{\widehat{\beta}_0},\quad  \hat{\beta}_0 + t_{\alpha/2,n-2}\,\widehat{\sigma}_{\widehat{\beta}_0})\\
{\beta}_1 \in (\hat{\beta}_1 - t_{\alpha/2,n-2}\,\widehat{\sigma}_{\widehat{\beta}_1},\quad \hat{\beta}_1 + t_{\alpha/2,n-2}\,\widehat{\sigma}_{\widehat{\beta}_1})
\end{align}\]</span></p>

<div class="rmdtip">
Decimos que, a nivel poblacional, <span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span> son estadísticamente cero si el intervalo de confianza contienen dicho valor.
</div>
<p>En nuestro ejemplo, podemos obtener los estadísticos de prueba para <span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span> utilizando el objeto <code>modelo</code> que contiene los resultados del modelo de RLS:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="rls.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="do">## estadísticos de prueba para beta_0 y beta_1</span></span>
<span id="cb44-2"><a href="rls.html#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(<span class="fu">summary</span>(modelo))</span></code></pre></div>
<pre><code>##               Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept) 15.7427499 0.17868164  88.10502 3.989520e-95
## Edad        -0.2437636 0.01310455 -18.60144 6.394519e-34</code></pre>
<p>En este caso, los estadístos de prueba se encuentran en la columna <code>t value</code> de la salida del <code>R</code>. Así, el estadístico para <span class="math inline">\(\beta_0\)</span> es <span class="math inline">\(t_0=88.1\)</span> y el estadístico para <span class="math inline">\(\beta_1\)</span> es <span class="math inline">\(t_1 = -18.6\)</span>. Por otro lado, los valores <span class="math inline">\(p\)</span> se encuentran en la columna <code>Pr(&gt;|t|)</code> y son, respectivamente, <span class="math inline">\(3.98\times 10^{-95}\)</span> y <span class="math inline">\(6.39\times 10^{-34}\)</span>. Puesto que ambos valores <span class="math inline">\(p\)</span> son <em>inferiores</em> a 0.05, concluimos que ambos parámetros son significativos (i.e., son diferentes de cero) a nivel poblacional con una confianza del 95%.</p>
<p>Para el mismo nivel de significancia, los intervalos de confianza pueden calcularse como en <code>R</code> a través de la función <code>confint.default</code>:</p>
<!-- Una manera más simple y rápida de construir intervalos de confianza del 95\% para $\beta_0$ y $\beta_1$ es utilizar la función `confint.default`: -->
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="rls.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="do">## intervalos de confianza via confint</span></span>
<span id="cb46-2"><a href="rls.html#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint.default</span>(modelo)</span></code></pre></div>
<pre><code>##                 2.5 %     97.5 %
## (Intercept) 15.392540 16.0929595
## Edad        -0.269448 -0.2180791</code></pre>
<p>Por lo tanto, con una confianza del 95%,</p>
<p><span class="math display">\[\begin{align}
\beta_0 &amp;\in(15.39, 16.09) \\
\beta_1 &amp;\in(-0.269, -0.218)
\end{align}\]</span></p>

<div class="rmdnote">
También es posible construir intervalos de confianza para los coeficientes del modelo utilizando la función <code>confint</code>. Sin embargo, estos difieren levemente de aquellos basados en la distribución <span class="math inline">\(t\)</span> o los construidos con la función <code>confint.default</code>. Esto se debe a que <code>confint</code> utiliza <a href="https://stats.stackexchange.com/questions/5304/why-is-there-a-difference-between-manually-calculating-a-logistic-regression-95">likelihood profiling</a>.
</div>
</div>
</div>
<div id="residuales" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> Análisis de Residuales</h2>
<p>El análisis de residuales es fundamental en RLS puesto que es posible establecer si:</p>
<ol style="list-style-type: decimal">
<li>Los errores del modelo ajustado cumplen con los supuestos;</li>
<li>existen observaciones atípias y/u observaciones influenciales.</li>
</ol>
<p>A continuación se describen las estrategias utilizadas para establecer 1 y 2.</p>
<div id="validación-de-supuestos" class="section level3 unnumbered">
<h3>Validación de Supuestos</h3>
<p>En la formulación matemática del modelo, se estableció que</p>
<p><span class="math display">\[\epsilon\sim N(0, \sigma^2), \hspace{1cm} \sigma^2 = \text{constante},\]</span>
y <span class="math inline">\(\epsilon_1, \epsilon_2, \ldots, \epsilon_n\)</span> son independientes. Por lo tanto, cuando se ajusta un modelo de RLS, debemos validar los siguientes supuestos sobre el error:</p>
<ol style="list-style-type: decimal">
<li>Independencia;</li>
<li>Normalidad;</li>
<li>Media cero; y</li>
<li>Varianza <span class="math inline">\(\sigma^2\)</span> constante.</li>
</ol>

<div class="rmdwarning">
Sólo cuando se han validado <strong>todos los supuestos del error</strong>, podemos proceder a realizar predicción de futuros valores de la variable respuesta con el modelo de RLS ajustado.
</div>
<div id="independencia" class="section level4 unnumbered">
<h4>Independencia</h4>
<p>Para validar el supuesto de independencia de los errores se recomiendan dos aproximaciones: la prueba formal de independencia de Durbin-Watson y la prueba gráfica basada en la Función de Autocorrelación (ACF en inglés).</p>

<div class="rmdnote">
<ul>
<li>La prueba de Durbin-Watson está implementada en la función <code>durbinWatsonTest</code> del paquete <code>car</code>.</li>
<li>La ACF puede obtenerse utilizando la función <code>acf</code>. Para más información escriba <code>?acf</code> en la consola del <code>R</code>.
</div></li>
</ul>
<p>En <code>R</code> podemos realizar la prueba de Durbin-Watson haciendo:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="rls.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="do">## prueba de Durbin-Watson </span></span>
<span id="cb48-2"><a href="rls.html#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(car)</span>
<span id="cb48-3"><a href="rls.html#cb48-3" aria-hidden="true" tabindex="-1"></a>car<span class="sc">:::</span><span class="fu">durbinWatsonTest</span>(modelo)</span></code></pre></div>
<pre><code>##  lag Autocorrelation D-W Statistic p-value
##    1     -0.02653343      2.050609   0.796
##  Alternative hypothesis: rho != 0</code></pre>
<p>Basados en el valor <span class="math inline">\(p\)</span>, <em>no</em> es posible rechazar <span class="math inline">\(H_0\)</span> puesto que el valor <span class="math inline">\(p\)</span> de la prueba de Durbin-Watson es superior a un nivel de significancia <span class="math inline">\(\alpha\)</span> del 5%. Por lo tanto, concluimos que los residuales del modelo ajustados <em>son</em> independientes.</p>
<p>Para graficar la ACF podemos hacer:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="rls.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="do">## ACF de los residuales</span></span>
<span id="cb50-2"><a href="rls.html#cb50-2" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">residuals</span>(modelo)  <span class="do">## cálculo de los residuales</span></span>
<span id="cb50-3"><a href="rls.html#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(r, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">main =</span> <span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-68-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>Para concluir que los residuales del modelo ajustado son <em>independientes</em> basados en la ACF, ninguna de las barras verticales, llamadas correlaciones, debe superar las bandas de color azul para <span class="math inline">\(\text{Lag} &gt; 0\)</span>. En nuestro caso, podemos concluir que los residuales <em>son</em> independientes.</p>
</div>
<div id="normalidad" class="section level4 unnumbered">
<h4>Normalidad</h4>
<p>Formalmente, probar el supuesto de normalidad de los errores equivale a realizar el siguiente procedimiento de prueba de hipótesis:</p>
<p><span class="math display">\[
\begin{split}
&amp;H_0: \text{los errores siguen una distribución Normal.} \\
&amp;H_A: \text{los errores NO siguen una distribución Normal.}
\end{split}
\]</span></p>
<p>Este supuesto puede validarse utilizando pruebas formales, o de manera gráfica utilizando histogramas, gráficos de densidad o un gráfico cuantil-cuantil, también conocido como <a href="https://es.wikipedia.org/wiki/Gr%C3%A1fico_Q-Q">Q-Q plot</a>.</p>
<p>Existen diferentes pruebas de Normalidad, varias de ellas implementadas en <code>R</code>.</p>

<div class="rmdnote">
<ul>
<li>Prueba Shapiro-Wilk, implementada en la función <code>shapiro.test</code>.</li>
<li>Prueba Anderson-Darling, implementada en la función <code>ad.test</code> del paquete <code>nortest</code>.</li>
<li>Prueba Cramer-von Mises, implementada en la función <code>cvm.test</code> del paquete <code>nortest</code>.</li>
<li>Prueba Lilliefors (Kolmogorov-Smirnov), implementada en la función <code>lillie.test</code> del paquete <code>nortest</code>.</li>
<li>Prueba Pearson basada en la distribución <span class="math inline">\(\chi^2\)</span>, implementada en la función <code>pearson.test</code> del paquete <code>nortest</code>.</li>
<li>Prueba Shapiro-Francia, implementada en la función <code>sf.test</code> del paquete <code>nortest</code>).
</div></li>
</ul>
<p>El Q-Q plot compara los cuantiles teóricos de la distribución Normal con los cuantiles muestrales del error estimado. Existen también varias implementaciones del gráfico cuantil-cuantil en <code>R</code>, entre las que se encuentran la función <code>qqnorm</code> del paquete <code>base</code> y la función <code>qqPlot</code> del paquete <code>car</code>.</p>
<p>Para realizar por ejemplo la prueba de Normalidad de Shapiro-Wilk sobre los residuales del modelo ajustado, podemos proceder de la siguiente forma utilizando el objeto <code>R</code> que contiene los resultados de dicho modelo:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="rls.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="do">## prueba de Normalidad de Shapiro-Wilk</span></span>
<span id="cb51-2"><a href="rls.html#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(r)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  r
## W = 0.98872, p-value = 0.5629</code></pre>
<p>Estos resultados indican que el valor <span class="math inline">\(p\)</span> de la prueba de Normalidad es <span class="math inline">\(p = 0.563\)</span>. Como <span class="math inline">\(p &gt; 0.05\)</span>, <strong>no</strong> rechazamos <span class="math inline">\(H_0\)</span> y concluimos que los residuales del modelo ajustado siguen una distribución Normal.</p>
<p>En <code>R</code>, podemos graficar un Q-Q plot de 2 formas:</p>
<p><strong>Vía gráficos básicos</strong></p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="rls.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Q-Q plot básico</span></span>
<span id="cb53-2"><a href="rls.html#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(r, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">main =</span> <span class="st">&quot;&quot;</span>)</span>
<span id="cb53-3"><a href="rls.html#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(r, <span class="at">col =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-71-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>Para más detalles, escribir <code>?qqnorm</code> en la consola del <code>R</code>. La idea fundamental es que los residuales del modelo (i.e., puntos en la gráfica) deben estar alrededor de la línea de color <em>rojo</em> para concluir, al menos gráficamente, que los residuales siguen una distribución Normal. En este caso, existen varios puntos por fuera de la línea, lo cual nos hace sospechar que esas observaciones <em>outliers</em> afectan el supesto.</p>
<p><strong>Utilizando el paquete car</strong></p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="rls.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Q-Q plot usando el paquete car</span></span>
<span id="cb54-2"><a href="rls.html#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car, <span class="at">quietly =</span> <span class="cn">TRUE</span>)</span>
<span id="cb54-3"><a href="rls.html#cb54-3" aria-hidden="true" tabindex="-1"></a>car<span class="sc">:::</span><span class="fu">qqPlot</span>(r, <span class="at">las =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-72-1.png" width="480" style="display: block; margin: auto;" /></p>
<pre><code>## [1] 77 18</code></pre>
<p>Aunque la elaboración de este gráfico es mucho más compleja, su interpretación es simple: diremos que los residuales del modelo ajustado <em>cumplen</em> con el supuesto de Normalidad si <em>todos</em> los puntos en encuentran <strong>dentro</strong> de las bandas de color <em>azul</em>. En este caso, las observaciones <code>18</code> y <code>77</code> parecen ser extremas.</p>
</div>
<div id="media-cero" class="section level4 unnumbered">
<h4>Media cero</h4>
<p>Formalmente la validación del supuesto de media cero para los errores consiste en probar</p>
<p><span class="math display">\[
\begin{split}
&amp;H_0: \mu_\epsilon=0 \\
&amp;H_A: \mu_\epsilon\neq0 
\end{split}
\]</span></p>
<p>donde <span class="math inline">\(\mu_\epsilon\)</span> es la media <em>poblacional</em> de <span class="math inline">\(\epsilon\)</span>.</p>
<p>Teniendo en cuenta que los coeficientes del modelo de RLS ajustado se obtienen a partir de MCO, no es necesario validar este supuesto. Básicamente, el método de MCO garantiza no rechazar <span class="math inline">\(H_0\)</span>. En caso de que se <strong>requiera</strong> hacerlo, podemos proceder de la siguiente manera en <code>R</code>:</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="rls.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="do">## validación media cero en RLS</span></span>
<span id="cb56-2"><a href="rls.html#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(r, <span class="at">mu =</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  r
## t = -3.6292e-16, df = 99, p-value = 1
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -0.1166475  0.1166475
## sample estimates:
##     mean of x 
## -2.133551e-17</code></pre>
<p>De este resultado es fácil ver que el valor <span class="math inline">\(p\)</span> de la prueba es <span class="math inline">\(p=1\)</span>, por lo que <strong>no</strong> rechazamos H_0. Finalmente concluimos, con una confianza del 95%, que la media de los residuales es cero a nivel poblacional.</p>
</div>
<div id="varianza-constante" class="section level4 unnumbered">
<h4>Varianza constante</h4>
<p>Por último, pero no menos importante, debemos validar el <strong>supuesto de varianza constante</strong>. Formalmente esto es equivalente a probar</p>
<p><span class="math display">\[
\begin{split}
&amp;H_0:\sigma^2 \text{ es constante}\\
&amp;H_1:\sigma^2 \text{ NO es constante}
\end{split}
\]</span></p>
<p>Esta prueba puede realizarse formalmente a través de diferentes pruebas estadísticas como la prueba de Breusch-Pagan, o utilizando métodos gráficos.</p>

<div class="rmdnote">
<ul>
<li>La prueba de Breusch-Pagan puede realizarse utilizando la función <code>ncvTest</code> del paquete <code>car</code>.</li>
<li>Los métodos gráficos consisten en construir gráficos de dispersión para <span class="math inline">\(\hat{y}\)</span> vs. <span class="math inline">\(y\)</span>, <span class="math inline">\(\hat{y}\)</span> vs. <span class="math inline">\(x\)</span> y <span class="math inline">\(\hat{y}\)</span> vs. el orden de medición. En el caso ideal, estos gráficos no deberían exhibir ningún patrón.
</div></li>
</ul>
<p><strong>Prueba de Breusch-Pagan</strong></p>
<p>Sin entrar en los detalles formales, la prueba de Breusch-Pagan busca determinar, estadísticamente, si la varianza del modelo de RLS ajustado es constante o no. En <code>R</code> podemos realizar esta prueba con a función <code>bptest</code> del paquete <code>lmtest</code>:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="rls.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="do">## prueba de Breusch-Pagan para varianza constante</span></span>
<span id="cb58-2"><a href="rls.html#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(lmtest)</span>
<span id="cb58-3"><a href="rls.html#cb58-3" aria-hidden="true" tabindex="-1"></a>lmtest<span class="sc">:::</span><span class="fu">bptest</span>(modelo)</span></code></pre></div>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  modelo
## BP = 9.7572, df = 1, p-value = 0.001786</code></pre>
<p>Como el valor <span class="math inline">\(p\)</span> de la prueba es mayor que 0.05, concluimos que la varianza del modelo <strong>no</strong> es costante.</p>
<p><strong>Aproximación gráfica</strong></p>
<p>Al usar esta aproximación, lo que buscamos es que los gráficos resultantes tenga un patrón aleatorio. En términos generales, podemos hacer gráficos de</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\hat{y}\)</span> vs. <span class="math inline">\(x\)</span>;</li>
<li><span class="math inline">\(\hat{y}\)</span> vs. <span class="math inline">\(r\)</span>; y</li>
<li><span class="math inline">\(\hat{y}\)</span> vs. orden de las observaciones,</li>
</ol>
<p>y evaluar los patrones observados.</p>
<!-- <center> -->
<!-- <img src="images/tablaanova.png" width="550" height="120"> -->
<!-- </center> -->
<p>Esencialmente, buscamos que ocurra el patrón del panel superior izquierdo <a href="https://www.rhayden.us/regression-models/images/3682_282_85-heteroscedasticity.jpg">aquí</a>.</p>
<p>En <code>R</code> podemos proceder de la siguiente manera:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="rls.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="do">## cálculos</span></span>
<span id="cb60-2"><a href="rls.html#cb60-2" aria-hidden="true" tabindex="-1"></a>y_hat <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo)  <span class="co"># valores predichos de y</span></span>
<span id="cb60-3"><a href="rls.html#cb60-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> datos<span class="sc">$</span>Edad  <span class="co"># seleccionamos el predictor</span></span>
<span id="cb60-4"><a href="rls.html#cb60-4" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> datos<span class="sc">$</span>Resistencia  <span class="co"># seleccionamos la variable respuesta</span></span>
<span id="cb60-5"><a href="rls.html#cb60-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-6"><a href="rls.html#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="do">## gráfico de residuales vs. valores predichos</span></span>
<span id="cb60-7"><a href="rls.html#cb60-7" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb60-8"><a href="rls.html#cb60-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(y_hat, r, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">main =</span> <span class="fu">expression</span>(<span class="fu">hat</span>(y) <span class="sc">*</span> <span class="st">&quot; vs. r&quot;</span>),</span>
<span id="cb60-9"><a href="rls.html#cb60-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">xlab =</span> <span class="fu">expression</span>(<span class="fu">hat</span>(y)), <span class="at">ylab =</span> <span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb60-10"><a href="rls.html#cb60-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="dv">2</span>)</span>
<span id="cb60-11"><a href="rls.html#cb60-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(y_hat, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">main =</span> <span class="fu">expression</span>(<span class="fu">hat</span>(y) <span class="sc">*</span> <span class="st">&quot; vs. orden&quot;</span>),</span>
<span id="cb60-12"><a href="rls.html#cb60-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">xlab =</span> <span class="st">&quot;Orden&quot;</span>, <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="fu">hat</span>(y)))</span>
<span id="cb60-13"><a href="rls.html#cb60-13" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(y, r, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">main =</span> <span class="fu">expression</span>(<span class="st">&quot;r vs. y&quot;</span>), <span class="at">ylab =</span> <span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb60-14"><a href="rls.html#cb60-14" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="dv">2</span>)</span>
<span id="cb60-15"><a href="rls.html#cb60-15" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, r, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">main =</span> <span class="fu">expression</span>(<span class="st">&quot;r vs. Edad&quot;</span>), <span class="at">ylab =</span> <span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb60-16"><a href="rls.html#cb60-16" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-76-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>De los gráficos anteriores se concluye que la varianza del modelo <em>no</em> es constante.</p>
<!-- ### Identificación de _outliers_{-} -->
<!-- ### Observaciones influenciales{-} -->
</div>
</div>
</div>
<div id="predicción" class="section level2" number="2.5">
<h2><span class="header-section-number">2.5</span> Predicción</h2>
<p>Sólo cuando se validan <strong>todos</strong> los supuestos del modelo es posible realizar predicción. La idea fundamental es poder calcular <span class="math inline">\(\widehat{E[Y|X=x_0]} = \widehat{\mu}|_{X=x_0}\)</span>, donde <span class="math inline">\(x_0\)</span> es un valor específico del factor controlable <span class="math inline">\(X\)</span>.</p>
<p>Adicionalmente, interesa construir intervalos de <strong>confianza</strong> e intervalos de <strong>predicción</strong> del <span class="math inline">\((1-\alpha)100\%\)</span> para <span class="math inline">\(\mu|_{X=x_0}\)</span>. Estos intervalos son fundamentales para determinar los valores máximos y mínimos del valor esperado de la respuesta <span class="math inline">\(Y\)</span> para valores puntuales de <span class="math inline">\(X\)</span> a nivel <strong>poblacional</strong>, para una confianza dada.</p>
<div id="intervalo-de-confianza-para-eyxx_0" class="section level3 unnumbered">
<h3>Intervalo de confianza para <span class="math inline">\(E[Y|X=x_0]\)</span></h3>
<p>Para <span class="math inline">\(\alpha\in(0,1)\)</span>, el intervalo de confianza del <span class="math inline">\((1-\alpha)100\%\)</span> para <span class="math inline">\(\mu |_{X=x_0}\)</span> está dado por:</p>
<p><span class="math display">\[\widehat{\mu} |_{X=x_0} \pm t_{\alpha/2,n-2}\,\hat{\sigma}\,\sqrt{\frac{1}{n} + \frac{(x_0-\bar{x})^2}{S_x}}\]</span></p>
</div>
<div id="intervalo-de-predicción-para-eyxx_0" class="section level3 unnumbered">
<h3>Intervalo de predicción para <span class="math inline">\(E[Y|X=x_0]\)</span></h3>
<p>Similarmente, el intervalo de predicción para <span class="math inline">\(Y |_{X=x_0}\)</span> será:</p>
<p><span class="math display">\[\widehat{\mu} |_{X=x_0} \pm t_{\alpha/2,n-2}\,\hat{\sigma}\,\sqrt{1+\frac{1}{n} + \frac{(x_0-\bar{x})^2}{S_x}}\]</span>
Observe que, aunque el intervalo de confianza y el intervalo de predicción están centrados en el mismo valor, el error estándar de <span class="math inline">\(\widehat{\mu} |_{X=x_0}\)</span> es mayor en el intervalo de predicción que en el intervalo de confianza, es decir,</p>
<p><span class="math display">\[
\sqrt{1+\frac{1}{n} + \frac{(x_0-\bar{x})^2}{S_x}} &gt; \sqrt{\frac{1}{n} + \frac{(x_0-\bar{x})^2}{S_x}}
\]</span></p>
<p>Esto se debe a que, al construir intervalos de predicción, la <strong>incertidumbre</strong> de <span class="math inline">\(\widehat{\mu} |_{X=x_0}\)</span> es mayor para valores de <span class="math inline">\(X\)</span> por fuera de las condiciones de operación evaluadas al recolectar la muestra.</p>

<div class="rmdnote">
<ul>
<li>Los <strong>intervalos de confianza</strong> permiten determinar el rango donde se encontrará el valor promedio de <span class="math inline">\(Y\)</span> para un valor específico de <span class="math inline">\(X\)</span> cuando se producen varias unidades experimentales en esas codiciones. Formalmente, esto es <span class="math inline">\(\widehat{\mu}|_{X=x_0} = \widehat{E[Y|X=x_0]}\)</span>.</li>
<li>Los <strong>intervalos de predicción</strong> permiten determinar el rango donde se encontrará <em>el próximo valor</em> de <span class="math inline">\(Y\)</span> cuando <span class="math inline">\(X=x_0\)</span>.
</div></li>
</ul>
<p>Aunque los residuales del modelo ajustado para los datos de soldadura <strong>no</strong> cumple con el supuesto de varianza constante, se mostrará cómo predecir la <code>Resistencia</code> de una soldadura con <span class="math inline">\(\text{Edad} = 20\)</span>, es decir, <span class="math inline">\(x_0=20\)</span>.</p>
<p>Con el objeto <code>modelo</code>, podemos construir el intervalo de confianza del 95% haciendo</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="rls.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="do">## intervalo de confianza del 95% para E[Resistencia|Edad = 20]</span></span>
<span id="cb61-2"><a href="rls.html#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(modelo, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Edad =</span> <span class="dv">20</span>), <span class="at">interval =</span> <span class="st">&quot;confidence&quot;</span>)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 10.86748 10.64805 11.08691</code></pre>
<p>Este resultado implica que, si medimos la Resistencia de <em>varias</em> soldaduras con <span class="math inline">\(\text{Edad} = 20\)</span>, se espera que la Resistencia promedio sea 10.87 psi, y que, a nivel <em>poblacional</em>, dicho promedio se encuentre en el intervalo <span class="math inline">\((10.65, 11.09)\)</span> con una confianza del 95%.</p>
<p>Finalmente, el intervalo de predicción cuando <span class="math inline">\(\text{Edad} = 20\)</span> será:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="rls.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="do">## intervalo de confianza del 95% para Resistencia|Edad = 20</span></span>
<span id="cb63-2"><a href="rls.html#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(modelo, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Edad =</span> <span class="dv">20</span>), <span class="at">interval =</span> <span class="st">&quot;prediction&quot;</span>)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 10.86748 9.674564 12.06039</code></pre>
<p>Por lo tanto, se espera que en <em>una</em> próxima soldadura de <span class="math inline">\(\text{Edad} = 20\)</span> el valor de Resistencia sea 10.87 psi. A nivel poblacional, dicha <code>Resistencia</code> estará en el intervalo <span class="math inline">\((9.67, 12.06)\)</span> el 95% de las veces.</p>
<!-- ## Ejemplos -->
<!-- 1. -->
<!-- 2. -->

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="rlm.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/jivelez/book-adii/edit/master/02-rls.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/jivelez/book-adii/blob/master/02-rls.Rmd",
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
